name: Check README.md in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR info
        id: pr_info
        run: |
          PR_NUMBER=$(echo ${{ github.event.pull_request.number }})
          PR_REPO=$(echo ${{ github.event.pull_request.head.repo.full_name }})
          COMMIT_HASH=$(echo ${{ github.event.pull_request.head.sha }})
          echo "::set-output name=pr_number::$PR_NUMBER"
          echo "::set-output name=pr_repo::$PR_REPO"
          echo "::set-output name=commit_hash::$COMMIT_HASH"

      - name: Check for README.md changes
        id: check_readme
        run: |
          git fetch origin ${{ github.sha }}
          FILES_CHANGED=$(git diff --name-only origin/${{ github.sha }})
          if echo "$FILES_CHANGED" | grep -q "README.md"; then
            echo "::set-output name=readme_changed::true"
          else
            echo "::set-output name=readme_changed::false"
          fi

      - name: Comment on PR
        if: steps.check_readme.outputs.readme_changed == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = ${{ steps.pr_info.outputs.pr_number }};
            const repository = "${{ steps.pr_info.outputs.pr_repo }}";
            const raw_url = `https://raw.githubusercontent.com/${repository}/${{ steps.pr_info.outputs.commit_hash }}/README.md`;
            const encoded_url = encodeURIComponent(raw_url);
            const preview_url = `https://dev-ui.57blocks.io/blog/preview?url=${encoded_url}`;
            const message = `The file has been modified, you can preview the modified file here: ${preview_url}`;
            github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
